### PR TITLE
[214-216] updated SecurityConfig.java, EmailServiceImpl.java

### PR DESCRIPTION
**Pull request by Fallstern**
Added check before sending a notification, now if there is no user with the provided email, NOTFOUND sends back

### CODE REVIEW

**Review by ViktorKapustianyk — APPROVED** [review]
The tests completed without issues, and the functionality operates as expected.

**Review by romanzeze — APPROVED** [review]

**Review by Nishant9771 — APPROVED** [review]
### It's a good practice to ensure that the email is only sent to valid .


import greencity.message.SendHabitNotification;
import greencity.message.SendReportEmailMessage;
import greencity.service.EmailService;
import greencity.service.UserService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class EmailController {
    @Autowired
    private final EmailService emailService;

    @Autowired
    private final UserService userService;

    /**
     * Method for sending news for users who subscribed for updates.
     */
    @PostMapping("/sendHabitNotification")
    public ResponseEntity<Object> sendHabitNotification(@RequestBody SendHabitNotification sendHabitNotification) {
        if (userService.findByEmail(sendHabitNotification.getEmail()) != null) {
            emailService.sendHabitNotification(sendHabitNotification.getName(), sendHabitNotification.getEmail());
            return ResponseEntity.status(HttpStatus.OK).build();
        }
        return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
    }
}

**Review by fedykvitalik2004 — APPROVED** [review]
I think it would be better to place the if-statement within the service layer.

**Review by IrynaVdovych — APPROVED** [review]

**Comment by Fallstern** [comment]
I'd like to ask for reapproval since I moved the logic to check if the email is present in the service layer. Also, add /error and move /senHabitNotification to be used only for admins in SecurityConfig.

**Review by IrynaVdovych — APPROVED** [review]

**Review by ViktorKapustianyk — APPROVED** [review]

**Pull request merged**
